In [ ]:
# DATA EXTRACTION & DATABASE LOADING

In [8]:
# IMPORT LIBRARIES

import os
import json
import mysql.connector
import pandas as pd

In [9]:
# HELPER FUNCTION TO CLEAN STATE NAMES

def clean_state_names(df):

    df["States"] = df["States"].str.replace("andaman-&-nicobar-islands", "Andaman & Nicobar")
    df["States"] = df["States"].str.replace("-", " ")
    df["States"] = df["States"].str.title()
    df["States"] = df["States"].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

    return df

In [ ]:
# DATA EXTRACTION

In [12]:
# AGGREGATED INSURANCE DATA EXTRACTION
# ------------------------------------

# aggregated_insurance_path = "pulse/data/aggregated/insurance/country/india/state/"
aggregated_insurance_path = "C:/vscode/phonepe/pulse/data/aggregated/insurance/country/india/state"

insurance_data = {
    "States": [],
    "Years": [],
    "Quarter": [],
    "Insurance_type": [],
    "Insurance_count": [],
    "Insurance_amount": []
}

for state in os.listdir(aggregated_insurance_path):
    state_path = os.path.join(aggregated_insurance_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as json_file:
                json_data = json.load(json_file)
                if json_data["data"]["transactionData"] is not None:
                    for item in json_data["data"]["transactionData"]:
                        insurance_data["States"].append(state)
                        insurance_data["Years"].append(int(year))
                        insurance_data["Quarter"].append(int(file.strip(".json")))
                        insurance_data["Insurance_type"].append(item["name"])
                        insurance_data["Insurance_count"].append(item["paymentInstruments"][0]["count"])
                        insurance_data["Insurance_amount"].append(item["paymentInstruments"][0]["amount"])

# Convert to dataframe
aggregated_insurance_df = pd.DataFrame(insurance_data)

# Clean state names
aggregated_insurance_df = clean_state_names(aggregated_insurance_df)

aggregated_insurance_df.head()

,States,Years,Quarter,Insurance_type,Insurance_count,Insurance_amount
0,Andaman & Nicobar,2020,2,Insurance,6,1360.0
1,Andaman & Nicobar,2020,3,Insurance,41,15380.0
2,Andaman & Nicobar,2020,4,Insurance,124,157975.0
3,Andaman & Nicobar,2021,1,Insurance,225,244266.0
4,Andaman & Nicobar,2021,2,Insurance,137,181504.0

In [ ]:
# AGGREGATED TRANSACTION DATA EXTRACTION
# ----------------------------------------

aggregated_transaction_path = "C:/vscode/phonepe/pulse/data/aggregated/transaction/country/india/state"

transaction_data = {
    "States": [],
    "Years": [],
    "Quarter": [],
    "Transaction_type": [],
    "Transaction_count": [],
    "Transaction_amount": []
}

for state in os.listdir(aggregated_transaction_path):
    state_path = os.path.join(aggregated_transaction_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as data_file:
                json_data = json.load(data_file)

                if json_data["data"]["transactionData"] is not None:

                    for transaction in json_data["data"]["transactionData"]:
                        transaction_data["States"].append(state)
                        transaction_data["Years"].append(int(year))
                        transaction_data["Quarter"].append(int(file.strip(".json")))
                        transaction_data["Transaction_type"].append(transaction["name"])
                        transaction_data["Transaction_count"].append(transaction["paymentInstruments"][0]["count"])
                        transaction_data["Transaction_amount"].append(transaction["paymentInstruments"][0]["amount"])


aggregated_transaction_df = pd.DataFrame(transaction_data)
aggregated_transaction_df = clean_state_names(aggregated_transaction_df)
aggregated_transaction_df.head()

,States,Years,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar,2018,1,Others,256,1.846899e+05

In [17]:
# AGGREGATED USER DATA EXTRACTION
# -----------------------------------

aggregated_user_path = "C:/vscode/phonepe/pulse/data/aggregated/user/country/india/state"

user_data = {
    "States": [],
    "Years": [],
    "Quarter": [],
    "Brands": [],
    "Transaction_count": [],
    "Percentage": []
}

for state in os.listdir(aggregated_user_path):
    state_path = os.path.join(aggregated_user_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as json_file:
                json_data = json.load(json_file)

                try:
                    for item in json_data["data"]["usersByDevice"]:
                        user_data["States"].append(state)
                        user_data["Years"].append(int(year))
                        user_data["Quarter"].append(int(file.strip(".json")))
                        user_data["Brands"].append(item["brand"])
                        user_data["Transaction_count"].append(item["count"])
                        user_data["Percentage"].append(item["percentage"])
                except:
                    pass


aggregated_user_df = pd.DataFrame(user_data)
aggregated_user_df = clean_state_names(aggregated_user_df)

aggregated_user_df.head()

              States  Years  Quarter   Brands  Transaction_count  Percentage
0  Andaman & Nicobar   2018        1   Xiaomi               1665    0.247033
1  Andaman & Nicobar   2018        1  Samsung               1445    0.214392
2  Andaman & Nicobar   2018        1     Vivo                982    0.145697
3  Andaman & Nicobar   2018        1     Oppo                501    0.074332
4  Andaman & Nicobar   2018        1  OnePlus                332    0.049258

In [18]:
# MAP INSURANCE DATA EXTRACTION
# ------------------------------

map_insurance_path = "C:/vscode/phonepe/pulse/data/map/insurance/hover/country/india/state"

map_insurance_data = {
    "States": [],
    "Years": [],
    "Quarter": [],
    "District": [],
    "Transaction_count": [],
    "Transaction_amount": []
}


# Loop through states
for state in os.listdir(map_insurance_path):
    state_path = os.path.join(map_insurance_path, state)

    # Loop through years
    for year in os.listdir(state_path):

        year_path = os.path.join(state_path, year)

        # Loop through quarter JSON files
        for file in os.listdir(year_path):

            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as json_file:
                json_data = json.load(json_file)

                # Extract district level insurance data
                for item in json_data["data"]["hoverDataList"]:

                    map_insurance_data["States"].append(state)
                    map_insurance_data["Years"].append(int(year))
                    map_insurance_data["Quarter"].append(int(file.strip(".json")))
                    map_insurance_data["District"].append(item["name"])
                    map_insurance_data["Transaction_count"].append(item["metric"][0]["count"])
                    map_insurance_data["Transaction_amount"].append(item["metric"][0]["amount"])


# Convert to dataframe
map_insurance_df = pd.DataFrame(map_insurance_data)

# Clean state names
map_insurance_df = clean_state_names(map_insurance_df)

map_insurance_df.head()

,States,Years,Quarter,District,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,south andaman district,3,795.0
1,Andaman & Nicobar,2020,2,nicobars district,3,565.0
2,Andaman & Nicobar,2020,3,north and middle andaman district,1,281.0
3,Andaman & Nicobar,2020,3,south andaman district,35,13651.0
4,Andaman & Nicobar,2020,3,nicobars district,5,1448.0

In [19]:
# MAP TRANSACTION DATA EXTRACTION
# ---------------------------------

map_transaction_path = "C:/vscode/phonepe/pulse/data/map/transaction/hover/country/india/state"

map_transaction_data = {
    "States": [],
    "Years": [],
    "Quarter": [],
    "District": [],
    "Transaction_count": [],
    "Transaction_amount": []
}

for state in os.listdir(map_transaction_path):

    state_path = os.path.join(map_transaction_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)
        
        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as json_file:
                json_data = json.load(json_file)
                
                for item in json_data["data"]["hoverDataList"]:

                    map_transaction_data["States"].append(state)
                    map_transaction_data["Years"].append(int(year))
                    map_transaction_data["Quarter"].append(int(file.strip(".json")))
                    map_transaction_data["District"].append(item["name"])
                    map_transaction_data["Transaction_count"].append(item["metric"][0]["count"])
                    map_transaction_data["Transaction_amount"].append(item["metric"][0]["amount"])


map_transaction_df = pd.DataFrame(map_transaction_data)
map_transaction_df = clean_state_names(map_transaction_df)

map_transaction_df.head()

,States,Years,Quarter,District,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,north and middle andaman district,442,9.316631e+05
1,Andaman & Nicobar,2018,1,south andaman district,5688,1.256025e+07
2,Andaman & Nicobar,2018,1,nicobars district,528,1.139849e+06
3,Andaman & Nicobar,2018,2,north and middle andaman district,825,1.317863e+06
4,Andaman & Nicobar,2018,2,south andaman district,9395,2.394824e+07

In [20]:
# MAP USER DATA EXTRACTION
# --------------------------

map_user_path = "C:/vscode/phonepe/pulse/data/map/user/hover/country/india/state"

map_user_data = {
    "States": [],
    "Years": [],
    "Quarter": [],
    "District": [],
    "RegisteredUser": [],
    "AppOpens": []
}

for state in os.listdir(map_user_path):
    state_path = os.path.join(map_user_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as json_file:
                json_data = json.load(json_file)

                # hoverData is dictionary
                for district, data in json_data["data"]["hoverData"].items():
                    map_user_data["States"].append(state)
                    map_user_data["Years"].append(int(year))
                    map_user_data["Quarter"].append(int(file.strip(".json")))
                    map_user_data["District"].append(district)
                    map_user_data["RegisteredUser"].append(data["registeredUsers"])
                    map_user_data["AppOpens"].append(data["appOpens"])

map_user_df = pd.DataFrame(map_user_data)
map_user_df = clean_state_names(map_user_df)

map_user_df.head()

,States,Years,Quarter,District,RegisteredUser,AppOpens
0,Andaman & Nicobar,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar,2018,1,south andaman district,5846,0
2,Andaman & Nicobar,2018,1,nicobars district,262,0
3,Andaman & Nicobar,2018,2,north and middle andaman district,911,0
4,Andaman & Nicobar,2018,2,south andaman district,8143,0

In [21]:
# TOP INSURANCE DATA EXTRACTION
# -------------------------------

top_insurance_path = "C:/vscode/phonepe/pulse/data/top/insurance/country/india/state"

top_insurance_data = {
    "States": [],
    "Years": [],
    "Quarter": [],
    "Pincodes": [],
    "Transaction_count": [],
    "Transaction_amount": []
}

for state in os.listdir(top_insurance_path):
    state_path = os.path.join(top_insurance_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as json_file:
                json_data = json.load(json_file)

                for item in json_data["data"]["pincodes"]:
                    top_insurance_data["States"].append(state)
                    top_insurance_data["Years"].append(int(year))
                    top_insurance_data["Quarter"].append(int(file.strip(".json")))
                    top_insurance_data["Pincodes"].append(item["entityName"])
                    top_insurance_data["Transaction_count"].append(item["metric"]["count"])
                    top_insurance_data["Transaction_amount"].append(item["metric"]["amount"])


top_insurance_df = pd.DataFrame(top_insurance_data)
top_insurance_df = clean_state_names(top_insurance_df)

top_insurance_df.head()

,States,Years,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,744301,3,565.0
1,Andaman & Nicobar,2020,2,744104,2,513.0
2,Andaman & Nicobar,2020,2,744101,1,282.0
3,Andaman & Nicobar,2020,3,744112,9,3432.0
4,Andaman & Nicobar,2020,3,744105,7,3948.0

In [22]:
# TOP TRANSACTION DATA EXTRACTION
# ---------------------------------

top_transaction_path = "C:/vscode/phonepe/pulse/data/top/transaction/country/india/state"

top_transaction_data = {
    "States": [],
    "Years": [],
    "Quarter": [],
    "Pincodes": [],
    "Transaction_count": [],
    "Transaction_amount": []
}

for state in os.listdir(top_transaction_path):
    state_path = os.path.join(top_transaction_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as json_file:
                json_data = json.load(json_file)

                for item in json_data["data"]["pincodes"]:
                    top_transaction_data["States"].append(state)
                    top_transaction_data["Years"].append(int(year))
                    top_transaction_data["Quarter"].append(int(file.strip(".json")))
                    top_transaction_data["Pincodes"].append(item["entityName"])
                    top_transaction_data["Transaction_count"].append(item["metric"]["count"])
                    top_transaction_data["Transaction_amount"].append(item["metric"]["amount"])

top_transaction_df = pd.DataFrame(top_transaction_data)
top_transaction_df = clean_state_names(top_transaction_df)

top_transaction_df.head()

,States,Years,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,744101,1622,2.769298e+06
1,Andaman & Nicobar,2018,1,744103,1223,2.238042e+06
2,Andaman & Nicobar,2018,1,744102,969,3.519060e+06
3,Andaman & Nicobar,2018,1,744105,685,1.298561e+06
4,Andaman & Nicobar,2018,1,744104,340,1.039715e+06

In [23]:
# TOP USER DATA EXTRACTION
# -----------------------------------

top_user_path = "C:/vscode/phonepe/pulse/data/top/user/country/india/state"

top_user_data = {
    "States": [],
    "Years": [],
    "Quarter": [],
    "Pincodes": [],
    "RegisteredUser": []
}

for state in os.listdir(top_user_path):
    state_path = os.path.join(top_user_path, state)

    for year in os.listdir(state_path):
        year_path = os.path.join(state_path, year)

        for file in os.listdir(year_path):
            file_path = os.path.join(year_path, file)

            with open(file_path, "r") as json_file:
                json_data = json.load(json_file)

                for item in json_data["data"]["pincodes"]:
                    top_user_data["States"].append(state)
                    top_user_data["Years"].append(int(year))
                    top_user_data["Quarter"].append(int(file.strip(".json")))
                    top_user_data["Pincodes"].append(item["name"])
                    top_user_data["RegisteredUser"].append(item["registeredUsers"])


top_user_df = pd.DataFrame(top_user_data)
top_user_df = clean_state_names(top_user_df)
top_user_df.head()

              States  Years  Quarter Pincodes  RegisteredUser
0  Andaman & Nicobar   2018        1   744103            1608
1  Andaman & Nicobar   2018        1   744101            1108
2  Andaman & Nicobar   2018        1   744105            1075
3  Andaman & Nicobar   2018        1   744102            1006
4  Andaman & Nicobar   2018        1   744104             272

In [ ]:
#  CONNECT TO MYSQL DATABASE

In [ ]:
import mysql.connector

mysql_connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root"
)

mysql_cursor = mysql_connection.cursor()

# Create and use database
mysql_cursor.execute("CREATE DATABASE phonepe_data")
mysql_cursor.execute("USE phonepe_data")

In [ ]:
# TABLE CREAION & INSERSION

In [26]:
# CREATE TABLE: AGGREGATED INSURANCE
# -------------------------------------

create_aggregated_insurance_table = """
CREATE TABLE IF NOT EXISTS aggregated_insurance (
    state_name VARCHAR(50),
    year INT,
    quarter INT,
    insurance_type VARCHAR(50),
    insurance_count BIGINT,
    insurance_amount BIGINT
)
"""

mysql_cursor.execute(create_aggregated_insurance_table)


# Insert aggregated insurance data
insert_aggregated_insurance = """
INSERT INTO aggregated_insurance
(state_name,year,quarter,insurance_type,insurance_count,insurance_amount)
VALUES (%s,%s,%s,%s,%s,%s)
"""

for index, row in aggregated_insurance_df.iterrows():

    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["Insurance_type"],
        row["Insurance_count"],
        row["Insurance_amount"]
    )

    mysql_cursor.execute(insert_aggregated_insurance, values)

mysql_connection.commit()

In [27]:
# CREATE TABLE: AGGREGATED TRANSACTION
# ----------------------------------------

create_aggregated_transaction_table = """
CREATE TABLE IF NOT EXISTS aggregated_transaction (
    state_name VARCHAR(50),
    year INT,
    quarter INT,
    transaction_type VARCHAR(50),
    transaction_count BIGINT,
    transaction_amount BIGINT
)
"""

mysql_cursor.execute(create_aggregated_transaction_table)


insert_aggregated_transaction = """
INSERT INTO aggregated_transaction
(state_name,year,quarter,transaction_type,transaction_count,transaction_amount)
VALUES (%s,%s,%s,%s,%s,%s)
"""

for index, row in aggregated_transaction_df.iterrows():

    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["Transaction_type"],
        row["Transaction_count"],
        row["Transaction_amount"]
    )

    mysql_cursor.execute(insert_aggregated_transaction, values)

mysql_connection.commit()

In [28]:
# CREATE TABLE: AGGREGATED USER
# -------------------------------------

create_aggregated_user_table = """
CREATE TABLE IF NOT EXISTS aggregated_user (
    state_name VARCHAR(50),
    year INT,
    quarter INT,
    brand VARCHAR(50),
    transaction_count BIGINT,
    percentage FLOAT
)
"""

mysql_cursor.execute(create_aggregated_user_table)


insert_aggregated_user = """
INSERT INTO aggregated_user
(state_name,year,quarter,brand,transaction_count,percentage)
VALUES (%s,%s,%s,%s,%s,%s)
"""

for index, row in aggregated_user_df.iterrows():

    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["Brands"],
        row["Transaction_count"],
        row["Percentage"]
    )

    mysql_cursor.execute(insert_aggregated_user, values)

mysql_connection.commit()

In [30]:
# CREATE TABLE: MAP INSURANCE
# -----------------------------

create_map_insurance_table = """
CREATE TABLE IF NOT EXISTS map_insurance (
    state_name VARCHAR(50),
    year INT,
    quarter INT,
    district VARCHAR(50),
    transaction_count BIGINT,
    transaction_amount FLOAT
)
"""

mysql_cursor.execute(create_map_insurance_table)


insert_map_insurance = """
INSERT INTO map_insurance
(state_name,year,quarter,district,transaction_count,transaction_amount)
VALUES (%s,%s,%s,%s,%s,%s)
"""

for index, row in map_insurance_df.iterrows():

    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["District"],
        row["Transaction_count"],
        row["Transaction_amount"]
    )

    mysql_cursor.execute(insert_map_insurance, values)

mysql_connection.commit()

In [31]:
# CREATE TABLE: MAP TRANSACTION
# -------------------------------

create_map_transaction_table = """
CREATE TABLE IF NOT EXISTS map_transaction (
    state_name VARCHAR(50),
    year INT,
    quarter INT,
    district VARCHAR(50),
    transaction_count BIGINT,
    transaction_amount FLOAT
)
"""

mysql_cursor.execute(create_map_transaction_table)


insert_map_transaction = """
INSERT INTO map_transaction
(state_name,year,quarter,district,transaction_count,transaction_amount)
VALUES (%s,%s,%s,%s,%s,%s)
"""

for index, row in map_transaction_df.iterrows():

    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["District"],
        row["Transaction_count"],
        row["Transaction_amount"]
    )

    mysql_cursor.execute(insert_map_transaction, values)

mysql_connection.commit()

In [35]:
# CREATE TABLE: MAP USER
# =-----------------------

create_map_user_table = """
CREATE TABLE IF NOT EXISTS map_user (
    state_name VARCHAR(50),
    year INT,
    quarter INT,
    district VARCHAR(50),
    registered_user BIGINT,
    app_opens BIGINT
)
"""

mysql_cursor.execute(create_map_user_table)


insert_map_user = """
INSERT INTO map_user
(state_name,year,quarter,district,registered_user,app_opens)
VALUES (%s,%s,%s,%s,%s,%s)
"""

for index, row in map_user_df.iterrows():

    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["District"],
        row["RegisteredUser"],
        row["AppOpens"]
    )

    mysql_cursor.execute(insert_map_user, values)

mysql_connection.commit()

In [36]:
# CREATE TABLE: TOP INSURANCE
# ------------------------------

create_top_insurance_table = """
CREATE TABLE IF NOT EXISTS top_insurance (
    state_name VARCHAR(50),
    year INT,
    quarter INT,
    pincode INT,
    transaction_count BIGINT,
    transaction_amount BIGINT
)
"""

mysql_cursor.execute(create_top_insurance_table)


insert_top_insurance = """
INSERT INTO top_insurance
(state_name,year,quarter,pincode,transaction_count,transaction_amount)
VALUES (%s,%s,%s,%s,%s,%s)
"""

for index, row in top_insurance_df.iterrows():

    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["Pincodes"],
        row["Transaction_count"],
        row["Transaction_amount"]
    )

    mysql_cursor.execute(insert_top_insurance, values)

mysql_connection.commit()

In [37]:
# CREATE TABLE: TOP TRANSACTION
# ----------------------------------

create_top_transaction_table = """
CREATE TABLE IF NOT EXISTS top_transaction (
    state_name VARCHAR(50),
    year INT,
    quarter INT,
    pincode INT,
    transaction_count BIGINT,
    transaction_amount BIGINT
)
"""

mysql_cursor.execute(create_top_transaction_table)


insert_top_transaction = """
INSERT INTO top_transaction
(state_name,year,quarter,pincode,transaction_count,transaction_amount)
VALUES (%s,%s,%s,%s,%s,%s)
"""

for index, row in top_transaction_df.iterrows():

    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["Pincodes"],
        row["Transaction_count"],
        row["Transaction_amount"]
    )

    mysql_cursor.execute(insert_top_transaction, values)

mysql_connection.commit()

In [38]:
# CREATE TABLE: TOP USER
# -------------------------

create_top_user_table = """
CREATE TABLE IF NOT EXISTS top_user (
    state_name VARCHAR(50),
    year INT,
    quarter INT,
    pincode INT,
    registered_user BIGINT
)
"""

mysql_cursor.execute(create_top_user_table)


insert_top_user = """
INSERT INTO top_user
(state_name,year,quarter,pincode,registered_user)
VALUES (%s,%s,%s,%s,%s)
"""

for index, row in top_user_df.iterrows():

    values = (
        row["States"],
        row["Years"],
        row["Quarter"],
        row["Pincodes"],
        row["RegisteredUser"]
    )

    mysql_cursor.execute(insert_top_user, values)

mysql_connection.commit()

In [ ]:
# CLOSE MYSQL CONNECTION

In [39]:
mysql_cursor.close()
mysql_connection.close()

print("All PhonePe datasets successfully loaded into MySQL!")

All PhonePe datasets successfully loaded into MySQL!